namespace :ci do
  namespace :git do
    task :test do
      sh("beaker",
          "--type", "git",
          "--load-path", "lib",
          "--hosts", ENV['CONFIG'],
          "--pre-suite", "setup",
          "--install", "PUPPET/#{ENV['PUPPET'] || 'master'},FACTER/#{ENV['FACTER'] || 'master'},HIERA/#{ENV['HIERA'] || 'master'}",
          "--tests", "tests",
          "--ntp",
          "--xml",
          "--debug",
          "--timeout", "1200",
          "--add-el-extras",
          "--keyfile", ENV['KEY'] || "#{ENV['HOME']}/.ssh/id_rsa")
    end
  end
end
