#!/bin/bash
#
# Make sure that old hiera cruft is removed
# This also allows us to downgrade facter as
# it's more likely that installing old versions
# over new will cause issues.
#
# ${3} is the destination volume so that this works correctly
# when being installed to volumes other than the current OS.

/bin/rm -Rf "${3}{SITELIBDIR}/hiera"
/bin/rm -Rf "${3}{SITELIBDIR}/hiera.rb"

# remove old doc files

/bin/rm -Rf "${3}/usr/share/doc/hiera"
