HOSTS:
  agent-solaris10-x86_64:
    roles:
      - agent
    platform: solaris-10-x86_64
    template: solaris-10-x86_64
    hypervisor: vcloud
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
